x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  server:
    image: judge0/judge0:latest
    container_name: server
    build:
      context: .
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    <<: *default-logging
    restart: always
    networks:
      - judge0-network

  worker:
    image: judge0/judge0:latest
    container_name: worker
    build:
      context: .
    environment:
      - COUNT=1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always
    networks:
      - judge0-network

  db:
    image: postgres:16.2
    env_file: judge0.conf
    container_name: db
    volumes:
      - data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always
    networks:
      - judge0-network

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    container_name: redis
    ports:
      - "6379:6379"
    <<: *default-logging
    restart: always
    networks:
      - judge0-network

volumes:
  data:

networks:
  judge0-network:
    name: judge0-network
    driver: bridge